@api_HostAddress = http://localhost:5165

POST {{api_HostAddress}}/ApiDescriptions?apiDescriptionUrl=https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml

### Add fantasyData API Description
POST {{api_HostAddress}}/ApiDescriptions?apiDescriptionUrl=https://fantasydata.com/downloads/swagger/soccer-v3-stats.json

### Get all College Basketball Teams stats
POST {{api_HostAddress}}/ApiDescriptions?apiDescriptionUrl=https://fantasydata.com/downloads/swagger/cbb-v3-stats.json

### Get Raptors stats
GET {{api_HostAddress}}/ApiOperations/search?query=get%20raptors%20stats 

### Did Man united win today?
GET {{api_HostAddress}}/ApiOperations/search?query=did%20man%20united%20win%20today 

### Get final result for Man united game today?
GET {{api_HostAddress}}/ApiOperations/search?query=get%20final%20result%20for%20man%20united%20game%20today 

### Translate "Hello World" to Klingon
GET {{api_HostAddress}}/ApiOperations/search?query=translate%20hello%20world%20to%20klingon

### Translate "Hello World" so that thrawn can understand
GET {{api_HostAddress}}/ApiOperations/search?query=translate%20hello%20world%20so%20that%20thrawn%20can%20understand


### Get API so I can talk to Chewbacka
GET {{api_HostAddress}}/ApiOperations/search?query=get%20api%20so%20i%20can%20talk%20to%20chewbacka


### Add Funtranslations API Description
POST {{api_HostAddress}}/ApiDescriptions?apiDescriptionUrl=http://api.funtranslations.com/yaml/funtranslations.yaml

### Add Twilio API Description
POST {{api_HostAddress}}/ApiDescriptions?apiDescriptionUrl=https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_api_v2010.json

### Add Giphy API Description
POST {{api_HostAddress}}/ApiDescriptions?apiDescriptionUrl=https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/giphy.com/1.0/openapi.yaml

### Search for a gif by keyword
GET {{api_HostAddress}}/ApiOperations/search?query=find%20an%20image%20based%20on%20a%20keyword 


### find a popular gif
GET {{api_HostAddress}}/ApiOperations/search?query=find%20a%20popular%20gif

### Search for a twilio account
GET {{api_HostAddress}}/ApiOperations/search?query=get%20a%20twilio%20account

### Create a twilio appplication
GET {{api_HostAddress}}/ApiOperations/search?query=create%20a%20twilio%20application

### Find an API that allows me to export Twilio jobs (doesn't work)
GET {{api_HostAddress}}/ApiOperations/search?query=exports%20twilio%20jobs%20between%20two%20dates


### Find an API that can store a secret
GET {{api_HostAddress}}/ApiOperations/search?query=store%20a%20secret

### Find an API that create an embedding
GET {{api_HostAddress}}/ApiOperations/search?query=create%20an%20embedding


### I want to eat thai
GET {{api_HostAddress}}/ApiOperations/search?query=I%20want%20to%20eat%20thai

